bihealth/reev-frontend-lib

package-lock.json

chore: testing release as 0.4.1

---

.eslintrc.cjs
package-lock.json
src/components/GeneOverviewCard/AlternativeIdentifiers.vue
src/components/GeneOverviewCard/ExternalResources.vue
src/components/GeneOverviewCard/GeneOverviewCard.spec.ts
src/components/GeneOverviewCard/GeneOverviewCard.stories.ts
src/components/GeneOverviewCard/GeneOverviewCard.vue
src/components/GeneOverviewCard/GeneRifs.vue
src/components/GeneOverviewCard/LocusDatabases.vue

feat: adding GeneOverviewCard

---

vitest.config.mts

chore: applying changes from prettier

---

README.md

docs: adding Zenodo DOI badge

---

src/components/GeneClinvarCard/VariationLandscapePlotly.vue

fix: Proper counting in variation landscape plot (#495)

---

src/components/SeqvarScoresCard/SeqvarScoresCard.vue

fix: Make buttons in Seqvars Scores card smaller (#520)

---

src/components/SeqvarFreqsCard/AutosomalFreqs.vue

fix: Make collapse buttons smaller for Population frqs card (#521)

---

src/components/GeneOverviewCard/GeneRifs.vue

fix: Omit permanent circular ncbi (#512)

---

src/components/GeneConditionsCard/GeneConditionsCard.vue

fix: Associated Conditions Card correctly sorts diseases and panels (#513)

---

src/components/GeneLiteratureCard/GeneLiteratureCard.vue

Add collapse button in literature section.

feat: Collapse Button for PubTator3 (#585)

---

src/api/annonars/index.ts
src/components/GeneConditionsCard/GeneConditionsCard.vue
src/components/GenomeBrowserCard/constants.ts
src/components/StrucvarToolsCard/StrucvarToolsCard.vue
src/lib/urlConfig.ts

fix: Nginx response 500 fro tracks reqeusts

---

src/api/pubtator/client.ts

fix: Pubtator3 new API responses adaptation (#643)

---

src/components/SeqvarToolsCard/SeqvarToolsCard.vue
src/components/StrucvarToolsCard/StrucvarToolsCard.vue

fix: do not prefix chromosomes with chr in igv link (#189)

---

src/components/GenomeBrowserCard/GenomeBrowserCard.vue

fix: genome browser not jumping to locus with grch38 (#202)

---

.github/workflows/release-please.yml

ci: disable building package release

---

src/api/variantValidator/client.ts

fix: variant validator URL needs trailing slash "/"

---

src/api/viguno/client.ts

feat: enable ignore case parameter for querying omim by name

---

src/api/viguno/client.spec.ts
src/api/viguno/client.ts

fix: viguno hpo search response for not found

---

src/api/variantValidator/client.ts

fix: variantvalidator query doesnt work (#234)

---

src/components/SeqvarFreqsCard/SeqvarFreqsCard.vue

fix: linting

---

src/components/SeqvarBeaconNetworkCard/SeqvarBeaconNetworkCard.vue

Just increased the height to 500px

feat: Increase height in BeaconNetwork card (#240)

---

src/stores/geneInfo/store.spec.ts

fix: varfish lint error

---

src/stores/pubtator/store.ts

fix: pubtator store loading with missing hgnc id (#243)

---

src/api/viguno/client.ts

fix: missing adapted viguno urls
